#!/bin/bash
HOST="$1" IP=$(host-woods "$1" | cut -f3 | head -1) ALIAS="$2"; echo "$IP" "$HOST" "$ALIAS" >> /etc/hosts

./addhost google.co.uk gu
./addhost google.com g 
./addhost twitter.com t
./addhost facebook.com f
./addhost github.com gi
./addhost bitbucket.org bi
./addhost amazon.co.uk am
./addhost ebay.co.uk eb
./addhost youtube.com y
./addhost aws.amazon.com aw
./addhost gandi.net ga
./addhost code.google.com/apis/console/ cog
